AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "wolfeidau: Cloudtrail log processor."

Parameters:
  AppName:
    Type: String
    Description: The name of the application.
  Stage:
    Type: String
    Description: The stage of development, e.g., dev, test, prod.
    Default: dev
  Branch:
    Type: String
    Description: The branch used to deploy.
    Default: master
  CloudtrailBucketName:
    Type: String
    Description: The name of the cloudtrail bucket to source files.
  CloudtrailTopicArn:
    Type: String
    Description: The name of the topic to monitor.
  SNSPayloadType:
    Type: String
    Description: The payload type in the SNS messages, e.g. cloudtrail or s3
    Default: cloudtrail

Conditions:
  IsProd:
    !Equals [!Ref Stage, "prod"]

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        STAGE: !Ref Stage
        BRANCH: !Ref Branch

Resources:
  ConfigValue:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/${Stage}/${Branch}/${AppName}/config"
      Type: String
      Value: |
        ---
        rules:
          - name: check_kms
            matches:
            - field_name: eventName
              regex: ".*crypt"
            - field_name: eventSource
              regex: "kms.*"

  CloudtrailOutputTopic:
    Type: AWS::SNS::Topic
    Properties: {}

  CloudtrailOutputTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - !Ref CloudtrailOutputTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: sns-s3
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Resource: !Ref CloudtrailOutputTopic
          Action: sns:Publish

  CloudtrailOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      NotificationConfiguration:
        TopicConfigurations:
        - Topic: !Ref CloudtrailOutputTopic
          Event: "s3:ObjectCreated:*"        

  CloudtrailOutputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudtrailOutputBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${CloudtrailOutputBucket}/*"
              - !Sub "arn:aws:s3:::${CloudtrailOutputBucket}"
            Condition:
              Bool:
                "aws:SecureTransport": "false"                

  CloudtrailS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/handler.zip
      Handler: filter-lambda
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref CloudtrailBucketName
        - S3WritePolicy:
            BucketName: !Ref CloudtrailOutputBucket
        - Version: '2012-10-17' 
          Statement:
            - Effect: "Allow"
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
                - ssm:GetParametersByPath
              Resource:
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ConfigValue}"
      Environment:
        Variables:
          CLOUDTRAIL_OUTPUT_BUCKET_NAME: !Ref CloudtrailOutputBucket
          CONFIG_SSM_PARAM: !Ref ConfigValue
          SNS_PAYLOAD_TYPE: !Ref SNSPayloadType
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref CloudtrailTopicArn

  CloudtrailS3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CloudtrailS3Function}"
      RetentionInDays: !If [IsProd, 365, 14]

Outputs:
  AppName:
    Value: !Ref AppName
  Stage:
    Value: !Ref Stage
  Branch:
    Value: !Ref Branch
  CloudtrailOutputBucketName:
    Value: !Ref CloudtrailOutputBucket
  CloudtrailOutputTopicArn:
    Value: !Ref CloudtrailOutputTopic
  CloudtrailS3LogGroupName:
    Value: !Ref CloudtrailS3LogGroup
